version: '2'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "lerna-test-root-pw"
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/my.cnf:/etc/mysql/my.cnf
